apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-long-cpu
spec:
  maxReplicas: 25
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 470
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 150
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: celery-worker-long
