apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: migrations
        image: [image]
        # imagePullPolicy: Always
        command: [ "/bin/bash","-c" ]
        args:
          - 
            mkdir -p /home/mediacms.io/mediacms/cms/;
            cp /home/mediacms.io/mediacms/deploy/docker/local_settings.py /home/mediacms.io/mediacms/cms/local_settings.py;
            python manage.py migrate;
            python manage.py loaddata fixtures/encoding_profiles.json;
            python manage.py loaddata fixtures/categories.json;
            python manage.py collectstatic --noinput
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        # env:
        # - name: ENABLE_UWSGI
        #   value: "no"
        # - name: ENABLE_NGINX
        #   value: "no"
        # - name: ENABLE_CELERY_BEAT
        #   value: "no" 
        # - name: ENABLE_MIGRATIONS
        #   value: "yes"
        # - name: ENABLE_CELERY_SHORT
        #   value: "no"
        # - name: ENABLE_CELERY_LONG
        #   value: "no"
      containers:
      - name: web
        image: [image]
        # imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENABLE_UWSGI
          value: "yes"
        - name: ENABLE_NGINX
          value: "yes"
        - name: ENABLE_CELERY_BEAT
          value: "no" 
        - name: ENABLE_MIGRATIONS
          value: "no"
        - name: ENABLE_CELERY_SHORT
          value: "no"
        - name: ENABLE_CELERY_LONG
          value: "no"             
        ports:
        - name: web
          containerPort: 80
        - name: uwsgi
          containerPort: 9000
          
        
      #   - name: TASK
      #     value: worker  
        volumeMounts:
          - mountPath: /home/mediacms.io/mediacms/media_files
            name: mediacms
            subPath: media_files
          - mountPath: /home/mediacms.io/mediacms/logs
            name: mediacms
            subPath: logs
            
      volumes:
        - name: mediacms
          persistentVolumeClaim:
              claimName: mediacms
              